[package]
name = "thyme"
version = "0.1.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
description = "Thyme GUI"
homepage = "https://github.com/Grokmoo/Grokmoo"
repository = "https://github.com/Grokmoo/Grokmoo"
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = { version = "0.4" }
image = { version = "0.23", default_features = false, features = [ "png" ] }
glium = "0.27"
winit = "0.22"
serde = { version = "1.0", features = [ "derive" ] }
rusttype = { version = "0.9" }

[dev-dependencies]
serde_yaml = "0.8"