[package]
name = "thyme"
version = "0.0.1"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
description = "Thyme GUI"
homepage = "https://github.com/Grokmoo/Grokmoo"
repository = "https://github.com/Grokmoo/Grokmoo"
readme = "README.md"
keywords = ["gamedev", "graphics", "gui"]
categories = ["game-development", "gui", "rendering"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = { version = "0.4" }
glium = "0.27"
winit = "0.22"
serde = { version = "1.0", features = [ "derive" ] }
rusttype = { version = "0.9" }
parking_lot = "0.11"

[dev-dependencies]
serde_yaml = "0.8"
image = { version = "0.23", default_features = false, features = [ "png" ] }