[package]
name = "thyme"
version = "0.2.0"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
description = "Themable Immediate Mode GUI"
documentation = "https://docs.rs/thyme/"
homepage = "https://github.com/Grokmoo/thyme"
repository = "https://github.com/Grokmoo/thyme"
readme = "README.md"
keywords = ["gamedev", "graphics", "gui"]
categories = ["game-development", "gui", "rendering"]
license = "Apache-2.0"
edition = "2018"
autoexamples = false

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "hello_glium"

[[example]]
name = "hello_wgpu"

[[example]]
name = "demo_glium"

[[example]]
name = "demo_wgpu"

[features]
default = []
glium_backend = ["glium"]
wgpu_backend = ["wgpu", "futures", "bytemuck" ]

[dependencies]
log = { version = "0.4" }
serde = { version = "1.0", features = [ "derive" ] }
rusttype = { version = "0.9" }
winit = "0.22"
parking_lot = { version = "0.11" }

image = { version = "0.23", optional = true, default_features = false, features = [ "png", "jpeg" ] }
glium = { version = "0.27", optional = true }
wgpu = { version = "0.6", optional = true }
futures = { version = "0.3", optional = true }
bytemuck = { version = "1", optional = true }

[dev-dependencies]
serde_yaml = "0.8"
image = { version = "0.23", default_features = false, features = [ "png" ] }