[package]
name = "thyme"
version = "0.0.1"
authors = ["Jared Stephen <grok_moo@yahoo.com>"]
description = "Thyme GUI"
homepage = "https://github.com/Grokmoo/thyme"
repository = "https://github.com/Grokmoo/thyme"
readme = "README.md"
keywords = ["gamedev", "graphics", "gui"]
categories = ["game-development", "gui", "rendering"]
license = "Apache-2.0"
edition = "2018"

[features]
default = []

glium_backend = ["glium"]
wgpu_backend = ["wgpu", "shaderc"]

[dependencies]
log = { version = "0.4" }
serde = { version = "1.0", features = [ "derive" ] }
rusttype = { version = "0.9" }
winit = "0.22"
parking_lot = { version = "0.11" }

glium = { version = "0.27", optional = true }
wgpu = { version = "0.6", optional = true }
shaderc = { version = "0.6", optional = true }

[dev-dependencies]
serde_yaml = "0.8"
image = { version = "0.23", default_features = false, features = [ "png" ] }